# Generated by Django 5.2.16 on 2026-08-06 13:23

import uuid

import django.utils.timezone  # type: ignore[import-untyped]
from django.db import migrations, models  # type: ignore[import-untyped]


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="MemoryEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("memory_id", models.UUIDField(db_index=True)),
                ("old_memory", models.TextField(blank=True, null=True)),
                ("new_memory", models.TextField(blank=True, null=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("ADD", "Add"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                ("actor_id", models.CharField(blank=True, max_length=255, null=True)),
                ("role", models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                "db_table": "memory_events",
                "ordering": ["updated_at"],
            },
        ),
    ]
