# Fresh databases create the final schema directly. Keep 0001 through 0010:
# partially migrated databases must still run their backfills and validation.
# This replacement runs only when none of those migrations were applied.
# Generated by Django 5.2.16 on 2026-10-07 04:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("chat", "0001_initial"),
        ("chat", "0002_conversationmessage"),
        ("chat", "0003_conversation_timestamps_and_title"),
        ("chat", "0004_conversation_execution"),
        ("chat", "0005_backfill_conversation_execution"),
        ("chat", "0006_add_memory_space_path_hash"),
        ("chat", "0007_backfill_memory_space_path_hash"),
        ("chat", "0008_add_owner_path_hash_unique"),
        ("chat", "0009_validate_memory_space_path_hash"),
        ("chat", "0010_finalize_memory_space_path_hash"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemorySpace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("workspace_path", models.TextField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_spaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("path_hash", models.CharField(max_length=64)),
            ],
            options={
                "indexes": [],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "path_hash"),
                        name="unique_owner_workspace_hash",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "memory_space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="chat.memoryspace",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(blank=True, default="", max_length=120)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [],
                "constraints": [],
            },
        ),
        migrations.CreateModel(
            name="ConversationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=16)),
                ("content", models.JSONField()),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
                "indexes": [],
                "constraints": [],
            },
        ),
        migrations.CreateModel(
            name="ConversationExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["idle", "running", "paused"])
                        ),
                        name="conversation_execution_valid_status",
                    )
                ],
                "indexes": [],
            },
        ),
    ]
