# Generated by Django 5.2.16 on 2026-10-02 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_conversation_timestamps_and_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["idle", "running", "paused"])
                        ),
                        name="conversation_execution_valid_status",
                    )
                ],
            },
        ),
    ]
