# Generated by Django 5.2.16 on 2026-10-02 08:06

from django.db import migrations


def create_missing_conversation_executions(apps, schema_editor):
    Conversation = apps.get_model("chat", "Conversation")
    ConversationExecution = apps.get_model("chat", "ConversationExecution")

    alias = schema_editor.connection.alias

    for conversation in Conversation.objects.using(alias).all().iterator():
        ConversationExecution.objects.using(alias).get_or_create(
            conversation_id=conversation.pk,
            defaults={"status": "idle"},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_conversation_execution"),
    ]

    operations = [
        migrations.RunPython(
            create_missing_conversation_executions,
            migrations.RunPython.noop,
        ),
    ]
