# Generated by Django 5.2.16 on 2026-10-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_backfill_conversation_execution"),
    ]

    operations = [
        migrations.AddField(
            model_name="memoryspace",
            name="path_hash",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
