# Generated by Django 5.2.16 on 2026-10-04 09:24
import hashlib

from django.db import migrations


def create_missing_hash_path(apps, schema_editor):
    MemorySpace = apps.get_model("chat", "MemorySpace")
    alias = schema_editor.connection.alias

    rows = MemorySpace.objects.using(alias).filter(path_hash__isnull=True)

    for row in rows:
        row.path_hash = hashlib.sha256(row.workspace_path.encode("utf-8")).hexdigest()

        row.save(using=alias, update_fields=["path_hash"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_add_memory_space_path_hash"),
    ]

    operations = [
        migrations.RunPython(
            create_missing_hash_path,
            noop_reverse,
        )
    ]
