# Generated by Django 5.2.16 on 2026-10-07 04:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_backfill_memory_space_path_hash"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="memoryspace",
            constraint=models.UniqueConstraint(
                fields=("owner", "path_hash"), name="unique_owner_workspace_hash"
            ),
        ),
    ]
