# Generated by Django 5.2.16 on 2026-10-07 04:29
import hashlib

from django.db import migrations


def validate_path_hashes(apps, schema_editor):
    MemorySpace = apps.get_model("chat", "MemorySpace")
    alias = schema_editor.connection.alias

    for row in MemorySpace.objects.using(alias).all().iterator():
        expected_hash = hashlib.sha256(row.workspace_path.encode("utf-8")).hexdigest()

        if row.path_hash != expected_hash:
            raise RuntimeError(f"工作区 {row.pk} 的路径摘要缺失或不一致")


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_add_owner_path_hash_unique"),
    ]

    operations = [
        migrations.RunPython(
            validate_path_hashes,
            migrations.RunPython.noop,
        ),
    ]
