# Generated by Django 5.2.16 on 2026-10-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_validate_memory_space_path_hash"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="memoryspace",
            name="unique_owner_workspace_memory_space",
        ),
        migrations.AlterField(
            model_name="memoryspace",
            name="path_hash",
            field=models.CharField(max_length=64),
        ),
    ]
